# Generated by Django 2.0 on 2020-12-13 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True, validators=[django.core.validators.RegexValidator("^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\-)|(:)|(\\')]+$")])),
                ('approved_status', models.IntegerField(default=1)),
            ],
        ),
    ]
