# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-29 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True, validators=[django.core.validators.RegexValidator(b"^[(A-Z)|(a-z)|(0-9)|(\\s)|(\\-)|(:)|(\\')]+$")])),
                ('approved_status', models.IntegerField(default=1)),
            ],
        ),
    ]
