# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-28 22:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.AlterModel(
            name='Volunteer',
            fields=[
                ('is_verified', models.BooleanField(default=False))
            ],
        ),
    ]
