repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: debug-statements
    -   id: end-of-file-fixer
        files: \.py$
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'flake8-quotes',
            'flake8-rst-docstrings',
            'pydocstyle>=5.0.0',
        ]
